apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: local-cert
  namespace: traefik
spec:
  dnsNames:
    - "local.root-g.com"
    - "*.local.root-g.com"
  commonName: "*.local.root-g.com"
  issuerRef:
    kind: ClusterIssuer
    name: local-issuer
  secretName: tls-local-letsencrypt
