apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: core
spec:
  destination:
    name: in-cluster
    namespace: argocd
  source:
    path: core
    repoURL: git@github.com:groot314/kubesCore.git
    targetRevision: HEAD
  sources: []
  project: default

