apiVersion: v1
kind: Namespace
metadata:
  name: metallb-system
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
spec:
  destination:
    name: in-cluster
    namespace: metallb-system
  source:
    repoURL: https://metallb.github.io/metallb
    targetRevision: 0.14.9
    chart: metallb
  project: default

