apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  name: nfs
spec:
  destination:
    name: in-cluster
    namespace: kube-system
  source:
    repoURL: >-
      https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts
    targetRevision: v4.10.0
    chart: csi-driver-nfs
  project: default
