apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  name: nfs-dev
provisioner: nfs.csi.k8s.io
parameters:
  server: 192.168.50.5
  share: /mnt/zpool/k8dev
reclaimPolicy: Retain
volumeBindingMode: Immediate
mountOptions:
  - nfsvers=4.1
