apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-external
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://traefik.github.io/charts
    chart: traefik
    targetRevision: 35.4.0
    helm:
      parameters:
        - name: installCRDs
          value: 'true'
      values: |-
        globalArguments:
          - "--global.sendanonymoususage=false"
          - "--global.checknewversion=false"
        additionalArguments:
          - "--serversTransport.insecureSkipVerify=true"
          - "--log.level=INFO"
        deployment:
          enabled: true
          replicas: 3
          annotations: {}
          podAnnotations: {}
          additionalContainers: []
          initContainers: []
        ports:
          web:
            redirections:
              entrypoint:
                to: websecure
                priority: 10
          websecure:
            http3:
              enabled: true
            advertisedPort: 4443
            tls:
              enabled: true
        ingressRoute:
          dashboard:
            enabled: false
        ingressClass:  
          enabled: true
          isDefaultClass: false
          name: "traefik-external"
        providers:
          kubernetesCRD:
            enabled: true
            ingressClass: traefik-external
            allowExternalNameServices: true
          kubernetesIngress:
            enabled: true
            allowExternalNameServices: true
            publishedService:
              enabled: false
        rbac:
          enabled: true
        service:
          enabled: true
          type: LoadBalancer
          annotations: {}
          labels: {}
          spec:
            loadBalancerIP: 192.168.70.55
          loadBalancerSourceRanges: []
          externalIPs: []
  destination:
    namespace: traefik-public
    name: in-cluster
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
